name: Github Action 실행하기

on:
  push:
    branches: main

jobs:
  My-First-CICD-Job:
    runs-on: ubuntu-latest

    steps:
      - name: simple-web-1
        run: |
          pwd
          ls -al
          echo "This is the first cicd step2" >> a.txt
      - name: simple-web-2
        run: |
          ls -al
          cat a.txt
      - name: simple-web-3
        run: |
          find . -name "index.html"

  My-Second-CICD-Job:
    runs-on: fedora-latest

    steps:
      - name: multiple-lines
        run: |
          echo "line 1"
          echo "line 2"
      - name: Github variables
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_RESPOSITORY
