name: Github Action 실행하기

on:
  push:
    branches: main

jobs:
  github-variables-check-job:
    runs-on: ubuntu-latest

    steps:
      - name: simple-web-1
        run: |
          pwd
          ls -al
          echo "This is the first cicd step2" >> a.txt
      - name: simple-web-2
        run: |
          ls -al
          cat a.txt
      - name: simple-web-3
        run: |
          echo GITHUB_SECRET
          echo GITHUB_REPOSITORY

  secret-variables-check-job:
    runs-on: ubuntu-latest

    steps:
      - name: secret-variables-check
        run: |
          echo "line 1"
          echo "line 2"
      - name: Github variables
        run: |
          echo ${{ secrets.EC2_USER}}
          echo ${{ secrets.EC2_PTM_KEY}}
