name: Github Action 실행하기

on:
  push:
    branches: main

jobs:
  My-First-CICD-Job:
    runs-on: ubuntu-latest

    steps:
      - name: simple-web
        run: |
          pwd
          ls -al
          echo "This is the first cicd step" >> a.txt
          ls -al
          cat a.txt
